language: php

##  PHP versions to test  against
php:
    - "7.0"
    - "5.6"
    - "5.5"
    - "5.4"
    - "5.3"
    - "5.2"
sudo: false
env:
    - WP_VERSION=master WP_MULTISITE=0
install:
  - chmod +x bin/install-dependencies.sh
  - ". ./bin/install-dependencies.sh"
script:
     grunt travis